### ISSUE TITLE
The div is not resizing after something changes inside the expanded container

### ISSUE THREAD

**Issue by tim-kilian** [dimensi/vue-slide-toggle#1]
## Problem
The expansion works well, but when I add a new div or increase the height, then its not resizing. 

## Possible solutions
- Add `height: auto` after transition 
- Detect changes and toggle transition
- Add middleware callbacks for beforeTransition and afterTransition

**Comment by dimensi** [comment]
Hi, can you give example on https://codesandbox.io/s/vue ? I expected this case so I added a height recalculation to the update hook.
https://github.com/dimensi/vue-slide-toggle/blob/master/src/SlideToggle.js#L27-L29

**Comment by tim-kilian** [comment]
Sure, I noticed that the update hook worked when the component updates. But when only the child component update, then the resize will not be triggered.

https://codesandbox.io/embed/7mv1xk3ylj

**Comment by dimensi** [comment]
Fix it. Check it https://codesandbox.io/s/mmyo5yz9lj

**Comment by tim-kilian** [comment]
Awesome! looks good to me. Thanks!
