### ISSUE TITLE
After install slide package couldn´t import it

### ISSUE THREAD

**Issue by webfacer** [dimensi/vue-slide-toggle#4]
Hi after i install the package i could not import it as compontent, it is like it was not installed. The docu says nothing about it, may be i forgot some step or there is another step to do and i do not know. Could you help me.

**Comment by dimensi** [comment]
Here is an example of a named component import.
```vue
<script>
import { VueSlideToggle } from "vue-slide-toggle";

export default {
  name: "App",
  components: { VueSlideToggle },
  data() {
    return {
      expanded: false
    };
  },
  methods: {
    expand() {
      this.expanded = !this.expanded;
    }
  }
};
</script>
```
And there's also an example in the sandbox: https://codesandbox.io/s/vue-template-5t1le

**Comment by webfacer** [comment]
did you try this link? it doesn´t work anymore since the issue here.

**Comment by dimensi** [comment]
![ezgif-2-810fcb3380d7](https://user-images.githubusercontent.com/11390039/62299064-e73d2800-b47c-11e9-834a-a26d1573492d.gif)

Sorry, but it works fine.

**Comment by webfacer** [comment]
hmmm intresting, tried also another browser (FireFox) and get "Blue Shield Warning
![Bildschirmfoto 2019-08-01 um 16 00 05](https://user-images.githubusercontent.com/137019/62299678-ab529480-b475-11e9-8eaf-d86b1c4a9b20.png)

and with crhome i get this
<img width="2560" alt="Bildschirmfoto 2019-08-01 um 16 00 13" src="https://user-images.githubusercontent.com/137019/62299667-a7bf0d80-b475-11e9-96c7-422968381fde.png">

hmm would it be possible to add it to another sandbox

**Comment by webfacer** [comment]
error i got when implementing VueSlideToggle:
Could not find a declaration file for module 'vue-slide-toggle'. '/opt/local/var/www/project_name/node_modules/vue-slide-toggle/dist/vue-slide-toggle.js' implicitly has an 'any' type.
  Try `npm install @types/vue-slide-toggle` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-slide-toggle'

**Comment by dimensi** [comment]
This is a warning from vscode, not a package error. Just ignore it and work with the package as specified in readme

**Comment by webfacer** [comment]
no this error comes when i run 'npm run serve' or build

**Comment by dimensi** [comment]
If you try using my package in typescript, then turn off static check then import or write declaration.

**Comment by webfacer** [comment]
oki thanks, and why pages didn´t worked, is because of our dns blocker service.

**Comment by webfacer** [comment]
if i just add it it shoots errors but it frontend gets rendered. But when i am looking at the test app´s component it does not render the component tag  as defined

**Comment by webfacer** [comment]
also when i am ignoring the typescript issue i got frontend issues:

`Unknown custom element: <vueslidetoggle> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`
